{
  # docs: https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#branch-types
  "branches": [
    {name: "main" },
    {name: "develop", channel: "alpha", prerelease: "alpha"},
    {name: "feature/**", channel: "beta", prerelease: "beta"},
    {name: "hotfix/**", channel: "beta", prerelease: "beta"}
  ],
  "plugins": [
  ["@semantic-release/commit-analyzer", {
    # docs: https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js
    "parserOpts": {
      "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
    },
    "preset": "conventionalcommits",
    "presetConfig": [ ]
  }],
  ["@semantic-release/release-notes-generator",{
    "parserOpts": {
      "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
    },
    "preset": "conventionalcommits",
    "presetConfig": [ ]
  }],
  '@semantic-release/github']
}
