<Project Sdk="MSTest.Sdk/4.3.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <Deterministic>true</Deterministic>

    <HxeCsproj>$([System.IO.Path]::GetFullPath("$(MSBuildProjectDirectory)/../../src/HXE.csproj"))</HxeCsproj>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(HxeCsproj)" Private="true" />
  </ItemGroup>
</Project>
