<Project Sdk="MSTest.Sdk/4.5.1">

  <PropertyGroup>
    <!-- If this is changed to TargetFramework, the build will fail because HXE won't be copied to the output directory -->
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/HXE.csproj" Private="true">
      <Properties>OutputType=Library;SelfContained=false;GeneratePackageOnBuild=false</Properties>
    </ProjectReference>
  </ItemGroup>
</Project>
