<Project Sdk="MSTest.Sdk/4.3.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/HXE.csproj" Private="true">
      <Properties>SelfContained=false</Properties>
    </ProjectReference>
  </ItemGroup>
</Project>
