name: ci

on:
  push:
    # ignore release branches; See file://./release.yml#on.push.branches , file://./../../.releaserc.ts
    branches-ignore: [main, develop]
    paths:
      - "!**/*.md"
      - "!**/*.txt"
  pull_request:
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5

      # if run simultaneously, the logs would be a mess
      - name: Build (Debug)
        run: dotnet build -c Debug -check

      - name: Pack (Release)
        run: dotnet pack

      - name: Publish (Release)
        run: dotnet restore -t:PublishAll
