name: ci
# This workflow demonstrates the minimal requirements for building the Solution with DotNet CLI


on:
  push:
    branches: [ main, develop ]
    paths-ignore:
    - '.github/workflows/'
    - '**/*.md'
    - '**/*.txt'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        buildConfig: [ "Release", "Debug" ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: ''

    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/HaloSPV3/index.json
        include-prerelease: true
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ################
    # BUILD
    ################

    - name: Build and Pack
      working-directory: ./src/
      run: dotnet pack HXE.csproj -c ${{ matrix.buildConfig }}
