name: Conventional Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review] # Currently, this action only support these events

jobs:
  hqprs:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          check_draft: true
          ignore_bot: true
          close: false
          link_issue: false
