name: Conventional Pull Request
# See https://github.com/Namchee/conventional-pr

on:
  pull_request:
permissions:
  checks: write
  issues: write
  pull-requests: write

jobs:
  hqprs:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.12.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
